### ISSUE TITLE
Test the working of  project and identify issue 

### ISSUE THREAD

**Issue by rishabhjoshi-rj** [JCM-Cloud-Systems/MysticalArena#1]
Setup the project as a contributor by appropriate use of git and github 
In open source, before you start contributing, first step is to understand the company's product yourself and test it to understand its flow. 
So, Explore the project, check its working, check all code in all class files, understand the logic. 
Check if mystic arena is working according the game rules
There is a issue so check it and fix it. 
Raise PR then.

**Comment by SoumyaJoshi06** [comment]
I want to take up this issue.

**Comment by rishabhjoshi-rj** [comment]
Merged, issue closed.
